# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Learn MPM 2D
author: Yongjin Choi
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Remove or adjust the latex section if necessary
# latex:
#   # Custom LaTeX configurations can be added here

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"

# Information about where the book exists on the web
repository:
  url: https://github.com/yjchoi1/learn-mpm-2d  # Online location of your book
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  baseurl: "/learn-mpm-2d"
  use_issues_button: true
  use_repository_button: true
